name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove unnecessary files
        run: |
          rm -f ./server.bat  # 배포하지 않을 파일 삭제

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # 현재 디렉토리의 모든 파일을 배포
          publish_branch: gh-pages  # 배포할 브랜치
